<?php

namespace App\Http\Models;

use App\Libraries\Flat\Entities\NewsEntity;
use App\Libraries\Flat\Model;
use App\Libraries\Flat\Collection;

/**
 * Class News
 * @package App\Http\Models
 */

/**
 * @property NewsEntity $entity
 */
class News extends Model
{
    /**
     * @var string $softDelete
     */
    protected $softDelete = 'is_deleted';

    /**
     * Set entity | Required
     * @return void
     */
    protected function setEntity()
    {
        $this->entity = new NewsEntity();
    }

    /**
     * @param null $condition
     * @return $this
     * @throws \Exception
     */
    public function load($condition = null)
    {
        return parent::load($condition); // TODO: Change the autogenerated stub
    }

    /**
     * Load collection
     * @param int $offset
     * @param int $segment
     * @param bool $all
     * @return Collection
     * @throws \Exception
     */
    public function loadCollection($offset = 0, $segment = 10, $all = false)
    {
        return parent::loadCollection($offset, $segment, $all); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $offset
     * @param int $segment
     * @param bool $all
     * @return array
     * @throws \Exception
     */
    public function loadArray($offset = 0, $segment = 10, $all = false)
    {
        return parent::loadArray($offset, $segment, $all); // TODO: Change the autogenerated stub
    }


}
